### ISSUE TITLE
[Bug]: Search bar dont work 

### ISSUE THREAD

**Issue by xTeAz2** [Fuzss/tradingpost#24]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

v8.0.2

### Other Mods Involved (Required)

Yes

### Notes (Required)

Search bar dont work if i type something in nothing happens.

### latest.log (Required)

No response

**Comment by Fuzss** [comment]
The search box is not selected by default. You need to click on it or press tab to select it.

**Comment by xTeAz2** [comment]
> The search box is not selected by default. You need to click on it or press tab to select it.

yes, I know, I can write in the field but the results are not filtered and nothing happens.

**Comment by Fuzss** [comment]
Can you reproduce the issue with just trading post + dependencies installed?

**Comment by shane1595042264** [comment]
> Yes did Work. So its the Modpack, im playing Prominece II Fabric. It has Version 8.0.1 installed but I tested 8.0.2 too

LOL I was having this issue earlier too, we are playing on the same modpack then.

**Comment by grappigegovert** [comment]
Like the other commenters, I noticed this same issue in the Prominence II modpack.
It appears to be a compatibility issue specifically with the mod "Item Obliterator" (https://www.curseforge.com/minecraft/mc-mods/item-obliterator)

**Comment by Fuzss** [comment]
No, it was simply an oversight on my end. It’s fixed in newer versions don’t remember if the fix made it to 1.20.1 should be in the changelog if it did.

**Comment by grappigegovert** [comment]
Version 8.0.2 of your mod did fix the issue of not being able to click the search bar, but the search still doesn't do anything if Item Obliterator (version 2.3.0) is also loaded.
You're able to write in the search bar, but all the trades stay visible regardless of what you type in.

**Comment by mdedmon** [comment]
I just updated to the Prominence II v3.0.11 and the mod was updated to the v8.0.2 and I'm having the identical issue to the previous poster (grappigegovert). Hope that a 1.20.1 fix will come at some time. ;)

**Comment by spencerfrost** [comment]
Can confirm that this isn't working in Prominence 2 still. @Fuzss would it be possible to get 1.20.1 updated with this fix as well?

**Comment by Fuzss** [comment]
Still can't reproduce the issue, everything is working fine with just Trading Post.
So assuming this is a mod conflict, would be great if someone could do some more testing to find out what is not working together correctly.

**Comment by grappigegovert** [comment]
As I mentioned a few posts earlier, the problem of the search not working in the Prominence 2 modpack is because this mod conflicts with the mod "Item Obliterator" (https://www.curseforge.com/minecraft/mc-mods/item-obliterator).
It is reproducible with just Trading Post (fabric-v8.0.2) and Item Obliterator (fabric-v2.3.0) (and the necessary libraries) enabled.
