### ISSUE TITLE
[Bug]: Stuck unloading server configs

### ISSUE THREAD

**Issue by GospelBG** [Fuzss/tradingpost#35]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

v21.0.2

### Other Mods Involved (Required)

No

### Notes (Required)

I play on a Fabric server with a large modpack with a friend. Whenever we try to stop the server (by running the `/stop` command), we can see that the server starts to save the world and unload everything, as it's supossed to do.
The problem is that it gets stuck when it starts to unload server configs, specially with `tradingpost-server.toml`, which always forces us to end up killing the java process in order to stop the server.

Further down there is the log file for the server startup and shutdown process. I am aware that there are a bunch of errors during the startup process, but this are not related to this mod.
I've also tried to remove every single mod but TradingPost and dependencies, it still happens. I've also added that server log (second one)

### latest.log (Required)

https://mclo.gs/FFyhl8l // https://mclo.gs/2QkGtlZ

**Comment by Fuzss** [comment]
That’s issue has been fixed for newer versions of Forge Config API port. They are only available for 1.21.1+ though, as 1.21 is not supported anymore. You can try to use the latest 1.21.1 build for 1.21 using dependency overrides though. 
https://wiki.fabricmc.net/tutorial:dependency_overrides

**Comment by GospelBG** [comment]
> You can try to use the latest 1.21.1 build

I've decided to upgrade the entire server to 1.21.1. But, despite using the latest version for 1.21.1 on Forge Config API Port, the issue persists.
